### PR TITLE
Add Plot module

### PR DESCRIPTION
**Pull request by oliveroxtoby**
See issue #122
Also discussed here: https://forum.freecadweb.org/viewtopic.php?f=10&t=35713
~The following pull request in the freecad.plot repository would need to be merged first for this to work: https://github.com/FreeCAD/freecad.plot/pull/7~ Edit: Done

### CODE REVIEW

**Comment by oliveroxtoby** [comment]
matplotlib is now working in the AppImages, so once this pull request is merged the CfdOF workbench will once again be operational in the latest release.

**Comment by luzpaz** [comment]
Deferring to @yorikvanhavre

**Comment by luzpaz** [comment]
@yorikvanhavre soft ping

**Comment by yorikvanhavre** [comment]
The problem is that @looooo chose not to implement the plot repo as a standard FreeCAD workbench. And therefore it cannot be added as a workbench by the addon manager. So I don't think it's a good idea to add it now, as it won't work for average users...

**Comment by oliveroxtoby** [comment]
@yorikvanhavre this was the aim of my commits in https://github.com/FreeCAD/freecad.plot/pull/7 ... it seems to work for me as a workbench now.

**Comment by oliveroxtoby** [comment]
I have tested installing and running it via the AddOn manager using my fork of this repo.

**Comment by yorikvanhavre** [comment]
Oh great, I wasn't aware of this. Okay, let's merge then!

**Comment by oliveroxtoby** [comment]
Thanks a lot :-) 
@luzpaz I did indeed put 'Resolves #122' in my commit message?

**Comment by luzpaz** [comment]
@oliveroxtoby dope! you totally did. I didn't look at the commit message but instead at the GH interface. My bad. Sorry for the noise :man_facepalming:

**Comment by oliveroxtoby** [comment]
@luzpaz No worries! Thanks for your help. :-)

**Pull request merged**
