### PR TITLE
Fix #61 (insufficient rights to create symlink)

### LINKED ISSUE #61: Creating a symlink on windows requires admin rights
When installing the BOLTSFC module, I am getting

```Traceback (most recent call last):
  File ".../AppData/Roaming/FreeCAD/Macro/addons_installer.FCMacro", line 665, in run
    symlink(clonedir+os.sep+f, macrodir+os.sep+f)
  File ".../AppData/Roaming/FreeCAD/Macro/addons_installer.FCMacro", line 69, in symlink
    raise ctypes.WinError()
WindowsError: [Error 1314] A required privilege is not held by the client.
```

This is caused by a Windows Security Policy which restricts symbolic link creation to Administrators: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766301(v=ws.10)#create-symbolic-links

I suggest to copy the file instead of creating a symlink on windows.

Alternatively, could modules directly be installed into the "Macro" directory, including their sub directories? Why is it required to install into "Mods" and then create a symlink of the macro file into the "Macro" directory?

### PR DESCRIPTION
**Pull request by wschildbach**
On Windows 10, symlink creation is not allowed unless the process runs with elevated rights. 

As per https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#joC5tFKhdXs2gGml.97, starting with Windows 10 Insiders build 14972, symlinks can be created without needing to elevate the console as administrator.

To use this functionality, 0x2 needs to be set in the flags argument for the CreateSymbolicLinkW() call. This fixes #61 .

A separate patch for the integrated AddOnManager is forthcoming.

### CODE REVIEW

**Comment by wschildbach** [comment]
Note that this still fails unless the user has [activated developer mode](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development). This should probably go into notes somewhere, or be printed when the symlink creation fails.

**Comment by luzpaz** [comment]
@wschildbach do you mind opening a thread on the FC Forums in regard to this issue for more community discussion ? Thanks

**Comment by luzpaz** [comment]
@sgrogan write in https://github.com/FreeCAD/FreeCAD-addons/issues/61#issuecomment-400139151  
> It should be good on Win10, I don't see a path to backwards compatibility on Win.

**Comment by yorikvanhavre** [comment]
This will actually only serve pre-0.17 versions (in 0.17 onwards it is bundled with FreeCAD itself, and IIRC symlinks are not used anymore on win) so I think we can consider this macro as deprecated now. I don't know if it's better to apply this patch or not..

**Comment by luzpaz** [comment]
is there a way to conditionally apply it if a user is running windows and pre-0.17 FC ?

**Comment by sgrogan** [comment]
I don't think the patch will cause any problems. No need to conditionally apply it, the question is how long to maintain the macro.

The only utility I see is if a user is using 0.16-legacy and using add-ons. Don't know how many add-ons work with this version.

IMHO the macro is obsolete, superseded by built in functionality, and can be removed from the repo.

**Comment by luzpaz** [comment]
Some on older machines still use 0.16 we've even seen 0.15 on the forums recently. 
Maybe we can make a note to merge and then revisit removal when 0.18 is removed ?

**Comment by yorikvanhavre** [comment]
I think we could remove the macro, it probably doesn't even work anymore...

**Comment by sgrogan** [comment]
Agreed

**Comment by wschildbach** [comment]
Seems the question is more about deployment than the code behavior, but let me know if I can help by testing...

**Comment by yorikvanhavre** [comment]
Okay we decided to remove the macro, because it is too old now, and, since the addon manager now seems to work for everybody, it would only be useful for pre-0.17 users, I don't think (I hope!) there are many left :) So this PR doesn't apply anymore... I'm closing it then, thanks anyway for the effort and help @wschildbach !

**Pull request closed without merging**
