### PR TITLE
Added ExtremProDark theme

### PR DESCRIPTION
**Pull request by MisterMakerNL**
Added ExtremProDark PreferencePack
It's my first pull request ever.
@[Chrismettal](https://github.com/Chrismettal) helped me to get it to work and tested it.

### CODE REVIEW

**Comment by luzpaz** [comment]
Awesome!  
Feedback: please convert tabs to the spaces in https://github.com/MisterMakerNL/ExtremeProDark/blob/main/package.xml (can be done easily in vscode)

**Comment by MisterMakerNL** [comment]
I changed it, although on my mobile since I'm away from my computer.

**Comment by luzpaz** [comment]
You missed a few tabs. I went ahead and reformatted the package.xml per the docs, see https://github.com/MisterMakerNL/ExtremeProDark/pull/1

**Comment by luzpaz** [comment]
Thanks!

**Pull request merged**
