### PR TITLE
Proxy settings

### LINKED ISSUE #57: AddonManager does not work behind corporate NTLM-proxy
Dear all,
There is no code to handle any proxy settings. This hampers the proliferation of FreeCAD in more traditional corporate settings.
To remedy this situation, I suggest to add:

a checkbox to turn on/off proxy support
a text field for proxy server and port
checkbox for "use authentication"
a textbox for username  (for proxy server)
a textbox for password (for proxy server)

the simplest form of adding support for the system-default proxy setting on Windows is: (this will not work for NTLM proxy, but at least "normal" proxies will work):
        proxy = urllib2.ProxyHandler()   #<--empty argument will use system-wide proxy from Windows network settings
        proxy_opener = urllib2.build_opener(proxy)
        urllib2.install_opener(proxy_opener)
        FreeCAD.Console.PrintWarning("Proxy set in UpdateWorker\n")

For NTLM-proxy support, you need to add this library: https://github.com/mullender/python-ntlm
There is an example on the page, but I have not fully succeeded in using it.

### PR DESCRIPTION
**Pull request by afester**
Partially fixes #57 (adds proxy support, but no NTLM support yet).

### CODE REVIEW

**Comment by luzpaz** [comment]
Anyone behind a proxy able to test this ?

**Comment by yorikvanhavre** [comment]
Note that with the upcoming release of FreeCAD 0.17, this installer macro will become obsolete. It might be interesting to port these changes to the AddonManager module of FreeCAD...

**Comment by afester** [comment]
@yorikvanhavre Yes I recognized that there is a different/new AddonManager module in Freecad 0.17 ... 
On the other hand, a better approach would be to provide a proxy settings panel in the Freecad Settings window so that all modules/macros can use those settings through FreeCAD.ParamGet(), instead of having all modules implement their own proxy settings panel (for example, I had the same issue when downloading the DXF import packages ...)

**Comment by yorikvanhavre** [comment]
Yes that is a good idea. Although at the moment the web functionality in FreeCAD is pretty reduced because Webkit has been kicked out of Qt5 and we need to switch all the web stuff to qwebengine... 

In the meantime, I'm merging your PR here so we have example code if we decide to port to the 0.17 addon manager before doing it freecad-wide...

**Comment by luzpaz** [comment]
Apparently this is still an issue: https://github.com/FreeCAD/FreeCAD-addons/issues/57#issuecomment-529383167

**Comment by luzpaz** [comment]
@yorikvanhavre i think we may have removed this Macro and with it the proxy settings availability. If so then we need to transfer the code in to master.

**Comment by luzpaz** [comment]
Yea, removed in a8a346359577b55005d0e6c4a55e1eef38df8a45

**Comment by yorikvanhavre** [comment]
The addons manager has changed a lot since then...
But here is the relevant code: https://github.com/FreeCAD/FreeCAD-addons/commit/6895172e55d846c82f3079745768074dde95fa53#diff-63d64650154b573102f30319d1f519d2

We now have a configuration panel for the addon manager as an ui file: https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/AddonManager/AddonManagerOptions.ui I think that would be the best place to configure proxy settings. Then, to cope with py2/py3 differences, all url handling code has been abstracted in a single function at https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/AddonManager/addonmanager_utilities.py#L86 I think the proxy mechanism could simply be added there

**Pull request merged**
