### PR TITLE
Updated BCF Plugin to v1.0.1

### PR DESCRIPTION
**Pull request by podestplatz**
The update to v1.0.1 fixes a typo in the bcfplugin/__init__.py file. The typo raises an exception when not all dependencies are available and an error shall be printed.

### CODE REVIEW

**Comment by luzpaz** [comment]
@podestplatz no need to make PRs for updates to your plugin. Since we're using the `git submodule` model which doesn't host the code on this repo but effectively 'symbolically links' to it. Any updates directly reflect when someone uses the Addon Manager.

**Comment by podestplatz** [comment]
Uh really? I thought that @yorikvanhavre linked my repo with a specific revision. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yorikvanhavre** [comment]
It's because we're using submodules in the addons repo, and git submodules are linked to a specific commit, which is what you see on github. However, the addons manager disregards the commit, and always grabs the current master revision. So no need to worry much with this. From time to time we do a general update of revision numbers, but it's not really necessary.

**Comment by podestplatz** [comment]
>It's because we're using submodules in the addons repo, and git submodules are linked to a specific commit, which is what you see on github. However, the addons manager disregards the commit, and always grabs the current master revision. So no need to worry much with this. From time to time we do a general update of revision numbers, but it's not really necessary.

@yorikvanhavre that explains it. Thanks for the merge, though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
