### PR TITLE
Add FreeCAD YAML Workspace

### PR DESCRIPTION
**Pull request by Mambix**
By @luzpaz suggestion I would like to add YAML workspace to this list.

It allows users to easily open multiple files and position them with the help of a simple YAML configuration file.

YAML config file used in the youtube video for demonstration:
```YAML
settings:
  subDirectory: stl
import:
  EATX:
    EATX:
      files:
        - BOTTOM.stl
        - LEFT.stl
      FRONT.stl:
        color: [.0, .0, 1.0]
        placement: [.0, 50.0, .0]
      BACK.stl:
        color: [.0, .0, 1.0]
        transparency: 50
      TOP.stl:
        color: green
        transparency: 50
        placement: [.0, .0, -5.0]
      RIGHT.stl:
        color: red
        transparency: 50
```

It crates a new document and imports six STL files. Some objects are left untouched, while others get moved. apply transparency and colour.

### CODE REVIEW

**Comment by luzpaz** [comment]
@Mambix do you mind also announcing this on the FreeCAD forums (to let the community know about this work)?

**Comment by Mambix** [comment]
@luzpaz I will. Was messing around with neo4j today 😋 

Was looking into this the other day but was not 100% sure where to put it. Is `Python scripting and macros` the correct place for new workspace announcement?

**Comment by easyw** [comment]
I would suggest Feature Announcements
https://forum.freecadweb.org/viewforum.php?f=9

**Comment by Mambix** [comment]
Post is currently waiting for approval on the forums 👍

**Comment by Mambix** [comment]
Forum post: https://forum.freecadweb.org/viewtopic.php?f=9&t=26750

**Pull request merged**
