### PR TITLE
Addon-manager: pyrate: changed repo url

### PR DESCRIPTION
**Pull request by joha2**
Hey @luzpaz and @yorikvanhavre 

I changed the repo url of pyrate, since we moved to salsa.debian.org. I hope that editing the .gitmodules file directly is the correct way to do this. If this is not the case, please feel free to reject the PR and I will perform the changes in an appropriate manner. (But you have to tell me, how to do it :-))

Best wishes
Johannes

### CODE REVIEW

**Comment by joha2** [comment]
Hey @chennes thanks for the hints! So at the end it is up to the user, whether the markdown library is installed on their system. Maybe from an UI perspective one can only provide a warning once the import is failed. For the package.xml file I implemented a first suggestion how it could look like in our salsa repo. Could you please have a look, whether this is OK?

https://salsa.debian.org/joha2/pyrate/-/blob/master/package.xml

A few comments:
* I added a `<comment>` tag to provide the information, that the repo should be cloned recursively. Obviously this is not the right place for this information. Do you see a possibility to perform the cloning recursively? (Either by a specific tag in the XML file or by using `git clone --recursive ...` as a default?)
* I hope the classname is correct. I used the class which is derived from `FreeCADGui.Workbench`.
* I left the `workbench` tag nearly empty, since all the necessary things like icon and so on are defined at top level already (maintainer = author in our case).
* The path to the icon is given in a relative form, do I need to use `./` in front?

I also saw, that you already provided code in one of the PRs for the addon manager in the main repo of FreeCAD due to my PR here. Thank you very much for that!

Best wishes
Johannes

**Comment by chennes** [comment]
A few points:

1. Recursive cloning is the default, so the Addon Manager will take care of it, you don't need to do anything for it to work.
2. I think that classname is correct.
3. You are missing the "<name>" tag from your workbench: it is probably "Pyrate" or "Pyrate Workbench" (however you want it to appear in the menu).
4. If you are only going to specify the icon in one place, put it as part of the workbench, rather than the package (the package will search for its icon in the workbenches if there isn't one specified, but workbenches require an icon).
5. Other than the icon, yes, it's correct that a content item will be mostly empty and inherit its information from the containing package.
6. Your icon path is correctly-formed.

**Comment by joha2** [comment]
Hey @chennes thanks for the review!

I moved the icon stuff between the workbench tags to reflect the necessity of the icon within workbench. What I did not understand is the `""` tag, you mentioned. Did you refer to the name tag within the workbench, which I forgot? I added a name tag to workbench to be in line with your example given in the FreeCAD documentation. Could you please have another look?

Thank you for your help!

When the package.xml is OK, is it possible to accept the PR or are there other blocking points?

Best wishes
Johannes

PS: I think for the adoption of the package.xml it would be useful to provide some kind of linter, which checks whether the package.xml fulfills the standards. What do you think?

**Comment by luzpaz** [comment]
Just ping me when PR needs merging :wink:

**Comment by chennes** [comment]
Yes, it was the `name` tag I was trying to refer to, but was thwarted by GitHub. The freecadmin and freecadmax tags are both optional, and are intended as informational for potential installers. The purpose of a freecadmax tag is that you could potentially distribute a package with two versions your workbench in it, one for older versions and one for newer, and the addon manager could handle which needed to go in.

And yes, a linter, as well as some other creation tools, are things I have in mind for the future.

**Comment by chennes** [comment]
I should also note that when this gets merged, no version of FreeCAD without the latest changes to Addon Manager (which haven't even been merged yet!) will be able to access pyrate. So I wouldn't be in a huge hurry for this! I'm considering back porting this support to 0.19.3, but haven't done so yet.

**Comment by joha2** [comment]
Hey @chennes and @luzpaz thanks for your help. I just removed the freecadmax tag, since it makes no sense as far as I know. Furthermore, for me the goal is that pyrate works frictionless in FreeCAD without any difficulties (although the GUI is not there and the API is not stabilized, yet). Therefore, the earlier we have the package.xml, the better. :smile: The most urgent task, anyway, is to update the repo link. So if everything is OK from your side @luzpaz you may merge this PR. I hope that, although the backporting of the package.xml stuff seems not that easy, backporting the salsa-stuff easier. :smiley: 

Again: Thank you for your fast help!

Best wishes
Johannes

**Comment by luzpaz** [comment]
Should we revisit this now?

**Comment by luzpaz** [comment]
@joha2 addon manager can support salsa: see https://github.com/FreeCAD/FreeCAD-addons/issues/80#issuecomment-1025228189

**Comment by chennes** [comment]
Yes, since 0.19.3 now also supports salsa, I think that as long as @joha understands that previous FreeCAD versions won't be able to install this addon after we merge this, then it's OK to move forward.

**Comment by joha2** [comment]
Sorry for my long response time! At the end, this should no big problem, since one can use multiple FreeCAD versions side by side. So thanks for making the necessary changes. I will close this issue.

**Pull request merged**
