### PR TITLE
Add Woodworking workbench

### PR DESCRIPTION
**Pull request by Andor**

### CODE REVIEW

**Comment by chennes** [comment]
Thanks! You have the wrong branch listed in your package.xml file, which will prevent the Addon Manager from working correctly. See line https://github.com/dprojects/Woodworking/blob/5c04998a431e3a3f7a2875e12e690182aef69ba1/package.xml#L10

("main" should be "master", or you should rename your primary branch)

**Comment by Andor** [comment]
@chennes thank you for the update. It is not my project, I am just a happy user.

**Comment by luzpaz** [comment]
cc @dprojects :point_up_2:

**Comment by Andor** [comment]
@chennes It is updated!

**Comment by luzpaz** [comment]
@chennes green light ?

**Pull request merged**
