### PR TITLE
add Better Tool Library addon to .submodules

### PR DESCRIPTION
**Pull request by knipknap**
This PR is for my new addon [Better Tool Library](https://github.com/knipknap/better-tool-library/).
As per the instructions, I also requested a Wiki account on the forum to add the addon to the Wiki.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
Excellent! Just wondering about the "btl" name... There is already a python module with that name: https://pypi.org/project/pybtl/ Maybe best to use another name, to avoid possible confusion?

**Comment by knipknap** [comment]
I think it's too late; my module is also already on Pypi: https://pypi.org/project/btl/

**Comment by yorikvanhavre** [comment]
Okay then, you were there first :smile:

**Comment by knipknap** [comment]
Thanks for merging!

**Pull request merged**
