### PR TITLE
Trails link update

### PR DESCRIPTION
**Pull request by HakanSeven12**
Old one doesn't works by intalling from addon manager. So I updated link.

### CODE REVIEW

**Comment by HakanSeven12** [comment]
Any interest on this?

**Comment by luzpaz** [comment]
@yorikvanhavre thoughts?

**Comment by luzpaz** [comment]
@joelgraff heads-up

**Comment by yorikvanhavre** [comment]
Sorry, missed that one :)
This looks good, but Trails != trails, so some users might have both installed, and this could lead to a lot of confusion. I'd rather keep the name "trails" without capital T, what do you think @HakanSeven12 ?

**Comment by HakanSeven12** [comment]
I don't think that's a big deal. Because old one can't be installable from addon manager for a long time. So if people are using it, they need to do a manual install. Those people are advanced users so it's not a problem for them. I prefer the 'Trails' 🙂

**Comment by yorikvanhavre** [comment]
Ok then.. Let's try, and keep an eye open if problems arise.

**Pull request merged**
