### PR TITLE
Add OSAFE workbench

### PR DESCRIPTION
**Pull request by ebrahimraeyat**
Related [issue](https://github.com/ebrahimraeyat/OSAFE/issues/27)

### CODE REVIEW

**Comment by luzpaz** [comment]
Thanks, we made the issue template for adding a workbench for this reason

![Screenshot_20230531_082037](https://github.com/FreeCAD/FreeCAD-addons/assets/4140247/8c018e16-b16d-4e3f-8f9f-83453bdf981

Do you mind filling it out?

**Comment by luzpaz** [comment]
@ebrahimraeyat please follow-up thx

**Comment by ebrahimraeyat** [comment]
Thanks @luzpaz . Related [issue](https://github.com/FreeCAD/FreeCAD-addons/issues/273)

**Comment by chennes** [comment]
This looks OK to me, if it's OK with @luzpaz . Please note that we will likely switch to compiling FreeCAD against Qt6 as our main version in the coming months, so you'll want to consider supporting that version (for the most part that will involve using `import PySide` instead of `import PySide2`, and letting FreeCAD insert the correct version at runtime).

**Comment by ebrahimraeyat** [comment]
I will change the import note, thanks @chennes .

**Comment by ebrahimraeyat** [comment]
I examined. It is not compatible  with FreeCAD 0.19, I will try to release a new version based on FreeCAD 0.21. I prepared it, but I can't compress the final output compiled, it take 800 MB size. Can I continue this problem in this issue? or in forum? Thanks.

**Comment by chennes** [comment]
Sure, wherever you like. I don't consider this a blocking issue here (unless you do).

**Pull request merged**
