### PR TITLE
Included Movie Workbench

### PR DESCRIPTION
**Pull request by Francisco-Rosa**
Add Movie Workbench

### CODE REVIEW

**Comment by Francisco-Rosa** [comment]
Add Movie Workbench

**Comment by Francisco-Rosa** [comment]
OK. The repository has already been renamed from main to master, as it does not derive from any other repository.

    Em sexta-feira, 16 de dezembro de 2022 15:18:25 BRT, Chris Hennes ***@***.***> escreveu:  
 
 


@chennes requested changes on this pull request.

You need to include branch = main (see Nodes for example), since your primary branch is not called "master".

**Comment by chennes** [comment]
That works too. I've just pushed a PR to you to fix two small errors in your package.xml file:
https://github.com/Francisco-Rosa/FreeCAD-Movie/pull/2

**Comment by chennes** [comment]
OK: next time you refresh your cache this should appear in the Addon Manager.

**Comment by Francisco-Rosa** [comment]
Amazing! Thank you!

    Em sábado, 17 de dezembro de 2022 19:48:55 BRT, Chris Hennes ***@***.***> escreveu:  
 
 


OK: next time you refresh your cache this should appear in the Addon Manager.

**Pull request merged**
