### PR TITLE
Update .gitmodules to add CadbaseLibrary

### PR DESCRIPTION
**Pull request by mnnxp**
Hello! I tried to take into account all the rules and write acceptable code. Please let me know if something is wrong and I will try to fix it. 

### Dependencies
- This Addon/workbench runs on:  
  - [x] Most up to date stable release
  - [ ] Most up to date development release
  - [x] Python 3 compatible
  - [x] Qt5 compatible
  - [x] Qt5 and Qt6 compatible (uses "import PySide" rather than "import PySide2")
- [x] Is this backward compatible with any previous version of FC? If so, please mention in the README.md
- [ ] Does this use 3rd party dependencies?  
  - [ ] numpy
  - [ ] scipy
  - [x] blake3 (optionaly)
  - Please specify if there are any other dependencies below and in the README.md and package.xml files

### README.md
- [x] Is [Markdown][Markdown-link] friendly
- [x] Has a **Prerequisite** or **Dependencies** section
- [x] Links to a ``LICENCE`` file (Note: FreeCAD uses LGPL2.1, most people choose that or GPL3)
- [x] Has a Screenshot and/or a section for screenshots
- [x] Links to a [FreeCAD Forum discussion thread][FreeCAD-Thread]

### Misc.
- [x] Do you keep a [changelog][Changelog]?  
  If so, where?
  At the bottom of the Readme.md
- [x] Your Addon has an SVG based Logo?
- [x] Your Addon has a [package.xml file][Package_Metadata]?
- [ ] Edit the FreeCAD [External Workbenches][FC-ExternalWB-Wiki] wiki page

### Housekeeping
- [ ] Fixed typos in the code using [`codespell`][Codespell]. We recommend running: `codespell -q 3`
The result of the `codespell -q 3` are some controversial remarks about name `nam`
- [ ] We recommend linting python code with PEP8. See [coding conventions][Code-conventions] 
The result of the check is some remarks such as single quotes, etc.

### Github Related
- [ ] Does your repository use [Release tags][Github-Tags] ?
- [x] Repository has [topics][Github-Topics] which include `FreeCAD` `Workbench` `Addon`  

**Note:** if your addon/workbench code doesn't reside on Github, please state the address where it is mentioned

 
[Markdown-link]: https://guides.github.com/features/mastering-markdown/
[FreeCAD-Thread]: https://forum.freecadweb.org/viewforum.php?f=8
[Changelog]: https://keepachangelog.com/en/1.0.0/
[Package_Metadata]: https://wiki.freecad.org/Package_Metadata
[FC-ExternalWB-Wiki]: https://www.freecadweb.org/wiki/External_workbenches
[Coding-conventions]: https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Fem/coding_conventions.md#python-and-c
[Codespell]: https://github.com/codespell-project/codespell
[Github-Topics]: https://help.github.com/en/articles/classifying-your-repository-with-topics
[Github-Tags]: https://help.github.com/en/articles/creating-releases

### CODE REVIEW

**Comment by chennes** [comment]
@luzpaz this looks good to me.

**Comment by luzpaz** [comment]
@chennes perhaps we should have a few more devs take a look at this? Also, an aside, is it necessary for git repos in the `.gitmodules` to have a `.git` extension? It looks like it's not necessary but just wanted to double check.

**Comment by chennes** [comment]
@luzpaz is there anyone in particular you think should review it? (and no, from an Addon Manager perspective the .git is totally unnecessary -- I don't know if it has any impact on the submodule rendering here on GitHub)

**Comment by luzpaz** [comment]
@chennes I'm not sure. But at some point we'll need to figure out how to vet addons (security wise). 

Anyway, I defer to you. Feel free to pull the trigger on this addon whenever you see fit.

**Comment by chennes** [comment]
Considering that it's substantially the same as the [CADbase macro](https://github.com/FreeCAD/FreeCAD-macros/tree/master/ImportExport/CadbaseLibrary) that's already included in our Macros repo, I think we can merge it. It would be good to have a better review process, but until one exists it's not really fair to block merges on the basis that we can't yet review these as thoroughly as we'd like to.

**Comment by mnnxp** [comment]
Thank you for your time!  
I'm very glad that this PR didn't cause any major difficulties.

**Pull request merged**
