### PR TITLE
Update ALLOWED_PYTHON_PACKAGES.txt for AnimationFreeCAD workbench

### PR DESCRIPTION
**Pull request by SHaiZen25**

### CODE REVIEW

**Comment by luzpaz** [comment]
Please describe what these python modules are for?

**Comment by SHaiZen25** [comment]
All these modules are required by Pyflow and if we don't add them Pyflow won't work

**Comment by chennes** [comment]
Shouldn't "pyflow" be the dependency then? Why do we have to manually install these?

**Comment by SHaiZen25** [comment]
We have just modified the "package.xml". Is it correct ?

**Comment by chennes** [comment]
No - you have "docutils" listed twice, and appear to be missing "blinker".

**Comment by SHaiZen25** [comment]
Yes, sorry for the mistake

**Comment by SHaiZen25** [comment]
After testing, the blinker, nine and docutils modules do not download when we install our module through the addon manager. Did we forget something ?

**Comment by chennes** [comment]
No, it's working fine for me -- do you have the latest version of FreeCAD? I only added support for this file a few days ago.

**Pull request merged**
