### PR TITLE
1A_WorkbenchOrganizer very first upload.

### PR DESCRIPTION
**Pull request by Palmstroemen**
This is the very first version of WBO (1A_WorkbenchOrganizer).
Sorry. I didn't understand how to 'tag' or 'label' my repository with 'FreeCAD', 'Workbench', 'AddOn'. 
If anyone can help, I'll be glad to resupply this.

### CODE REVIEW

**Comment by Palmstroemen** [comment]
Ahhrg! What's that pre-commit.ci - pr thing here? This GitHub is driving me crazy. There is no such file in my repository.

**Comment by chennes** [comment]
Ignore the CI failure.

**Comment by chennes** [comment]
You should set up your own GitHub/Gitlab/whatever repo, and point this repo's .gitmodules at it -- none of the Addons you see here are actually part of this repo (if they were it would require FreeCAD Maintainers to approve every change to your Addon).

**Comment by Palmstroemen** [comment]
Unfortunately I do not understand this. What does that mean: "point this repo's gitmodules at it"? How would I do that.
My GitHub-Repository is: [(https://github.com/Palmstroemen/WB_Organizer)]
Unfortunately GitHub appends a '_main' to my folder name on download. So on download people get an 'WB_Organizer_main.zip' file that then expands into a 'WB_Organizer_main' folder. 

Thank you very much for helping me out.

**Comment by chennes** [comment]
You need for fork this repo, and instead of adding your code to it directly, instead just edit .gitmodules -- in there you will see a list of the Addons. Add yours in alphabetically (without the "1A" prefix, please).

**Pull request closed without merging**
