### PR TITLE
added slic3r tools

### PR DESCRIPTION
**Pull request by limikael**
This adds a workbench for using FreeCAD and Slic3r for 3D printing, without having to manually go through the many clicks of exporting and running Slic3r manually.

Here is a discussion on the forum:

https://forum.freecadweb.org/viewtopic.php?f=9&t=36342

### CODE REVIEW

**Comment by luzpaz** [comment]
Thanks @limikael  
@yorikvanhavre deferring to you on this decision :stuck_out_tongue_winking_eye:

**Comment by yorikvanhavre** [comment]
Great work @limikael !! Thanks!!

**Comment by luzpaz** [comment]
@limikael can you please also add your workbench to the https://github.com/FreeCAD/FreeCAD-addons/blob/master/FreeCAD-Addon-Details.md file?

**Comment by limikael** [comment]
Thanks guys! Very proud to have made a contribution!

@luzpaz The description for the addon details is in this PR: https://github.com/FreeCAD/FreeCAD-addons/pull/132

**Pull request merged**
