### PR TITLE
Update issue templates

### LINKED ISSUE #131: Add a PULL_REQUEST_TEMPLATE.md
Add a similar template like https://github.com/FreeCAD/FreeCAD/blob/master/.github/PULL_REQUEST_TEMPLATE.md

We should ask people to complete several tasks:  
- proper README. Markdown friendly  
- README has a link to a discussion forum for feedback/discussion  
- README has screenshots  
- Py3/Qt5 compatible
- Run `codespell` to remove typos
- more ?

### PR DESCRIPTION
**Pull request by luzpaz**
Experimenting with an issue template.  
Closes #131

### CODE REVIEW

**Comment by luzpaz** [comment]
@yorikvanhavre What do you think?

**Comment by yorikvanhavre** [comment]
Looks perfect! Maybe add a checkbox with python3 compatibility, although I suppose from now on all new workbenches will be python3...

**Comment by luzpaz** [comment]
@yorikvanhavre 
Duh, i forgot to add that. ec756c1  
Actually, I had originally added it and foolishly lost it in some silly keyboard shortcut browser closing accident :cry:  Anyway, here we are. Ready for merge ?

**Comment by yorikvanhavre** [comment]
Sure, go ahead!

**Pull request closed without merging**
