### PR TITLE
Change 'Exploded Animation' to 'Exploded Assembly'

### LINKED ISSUE #55: Change repos:  'Exploded Animation' > 'Exploded Assembly'
Currently it shows  exploded_animation @ 9feccab
the updated repo is https://github.com/JMG1/ExplodedAssembly

### PR DESCRIPTION
**Pull request by luzpaz**
Closes #55
I think i'm missing something. Please review.

### CODE REVIEW

**Comment by yorikvanhavre** [comment]
This PR removes the Webtools submodule...

**Comment by luzpaz** [comment]
Yikes, have no idea how that happened. Fixed in 67736f3

**Comment by luzpaz** [comment]
@yorikvanhavre I'm not sure I did this correctly. I manually edited the .gitconfig file. Does anything else need to happen ?

**Comment by yorikvanhavre** [comment]
I think the directory itself needs to be changed too, no? Does it work for you locally on your computer?

**Pull request closed without merging**
