### PR TITLE
EM Workbench addition

### PR DESCRIPTION
**Pull request by ediloren**
Hi, I've added the EM Workbench in the addons (as discussed in the FreeCAD forum under FEM, see https://forum.freecadweb.org/viewtopic.php?f=18&t=31920) 

I will also now post under Announcements in the Forum to advertise the availability of the Workbench.

Wiki addon pages are updated:

https://freecadweb.org/wiki/External_workbenches
https://www.freecadweb.org/wiki/Template:DevWorkbenches

Documentation is complete under 

https://www.freecadweb.org/wiki/EM_Workbench

Thanks for pulling!

Enrico

### CODE REVIEW

**Comment by luzpaz** [comment]
Very cool indeed.  
Punting decision to @yorikvanhavre

**Comment by ediloren** [comment]
Hi @luzpaz and @yorikvanhavre , 

any chance for the pull? In case, if you give me the rights, I can do that myself (as I'm also moderator on the FreeCAD forum etc. I hope you trust me...).

Thanks
Enrico

**Comment by yorikvanhavre** [comment]
Damn, sorry guys, I missed this one... I'll give you commit rights on the repo @ediloren

**Comment by yorikvanhavre** [comment]
Added with b0f352e

**Comment by ediloren** [comment]
Thanks Yorik. No issue, I know that it's done when it's done :) but I'm really happy that now everybody can install the E.M. workbench in FreeCAD with a click of the mouse!

**Pull request closed without merging**
