### PR TITLE
Add pyqt-node-editor(nodeeditor) + qtpy to ALLOWED_PYTHON_PACKAGES

### PR DESCRIPTION
**Pull request by luzpaz**
In preparation for #231 and https://github.com/j8sr0230/fc_nodes/issues/5

### CODE REVIEW

**Comment by chennes** [comment]
Wrong name - its actual name is just "nodeeditor".

**Comment by luzpaz** [comment]
Thanks, It also depends on qtpy (https://github.com/spyder-ide/qtpy)

**Comment by luzpaz** [comment]
Thanks, It also depends on qtpy (https://github.com/spyder-ide/qtpy)

**Comment by luzpaz** [comment]
Wait are we differentiating the node editor correctly? 
There is a https://github.com/paceholder/nodeeditor 
We want https://gitlab.com/pavel.krupala/pyqt-node-editor

**Comment by chennes** [comment]
https://pypi.org/project/nodeeditor/

**Pull request merged**
