### PR TITLE
added curved shapes workbench

### PR DESCRIPTION
**Pull request by chbergmann**

### CODE REVIEW

**Comment by luzpaz** [comment]
@yorikvanhavre WB is at https://github.com/chbergmann/CurvedShapesWorkbench 
If you merge it then add `Closes #135` in the commit message. :wink:

**Comment by yorikvanhavre** [comment]
PRs get automatically closed when merged... No need to add to the commit message.

**Comment by luzpaz** [comment]
oh duh, forgot this was a PR :man_facepalming:

**Comment by luzpaz** [comment]
Wait, @yorikvanhavre, the workbench wasn't added to the repo, the PR was just to modify the `FreeCAD-Addon-Details.md`.

**Comment by luzpaz** [comment]
OK, Workbench was added in 5bcc70ba2fe

**Pull request merged**
