### PR TITLE
Added scikit-learn to ALLOWED_PYTHON_PACKAGES.txt

### PR DESCRIPTION
**Pull request by tBuLi**
Added scikit-learn to ALLOWED_PYTHON_PACKAGES.txt.

### CODE REVIEW

**Comment by luzpaz** [comment]
Deferring to @chennes

**Comment by chennes** [comment]
No problems from me, this is a major package.

**Comment by tBuLi** [comment]
Thanks for the quick resolution!

**Comment by luzpaz** [comment]
@tBuLi can you link to what you're using the library for?

**Pull request merged**
